[package]
name = "jymbol"
version = "0.1.0"
edition = "2024"
authors = ["Jordan Danford <jordandanford@gmail.com>"]

[dependencies]
anyhow = "1.0"
chumsky = "0.8"
dumpster = "1.1"
im = "15"
intmap = "3.1"
symbol_table = "0.3"

[profile.release]
debug = true
