[package]
name = "jymbol"
version = "0.1.0"
edition = "2021"
authors = ["Jordan Danford <jordandanford@gmail.com>"]

[dependencies]
chumsky = "0.8"
im = "15"
lazy_static = "1.4"
logos = "0.12"
symbol_table = { version = "0.3", features = ["global"] }
unescaper = "0.1"
