[package]
name = "jymbol"
version = "0.1.0"
edition = "2021"
authors = ["Jordan Danford <jordandanford@gmail.com>"]

[dependencies]
chumsky = "0.8"
gc = { version = "0.4", features = ["derive"] }
im = "15"
once_cell = "1.17"
symbol_table = "0.3"
